Update git-pack to 0.14.0
git-pack 0.13.0 was causing a panic during replication. Specifically
like this:

thread 'blocking-42' panicked at 'assertion failed: `(left == right)`
left: `4`, right: `3`: This should not happen unless we added more nodes
    than were declared in the constructor',
    <git pack crate>/src/cache/delta/iter.rs:8:9

git-pack 0.14.0 does not have this problem. This patch gets
replication-v3 to pass all the Upstream integration tests.